name=TeensyXENO
version=1.2.0
author=XENOCROSS AEROSPACE SYSTEM
maintainer=Katsushi Mitsutake <mitutake@xenocross.com>
sentence=Teensy-based XENO controller library.
paragraph=TeensyXENO is a library for SBUS I/O, XenoController communication, PWM output, and HILS support on TeensyXENO boards.
category=Communication
url=https://github.com/mitutake0422/TeensyXENO
architectures=teensy
