name=TeensyXENO
version=1.0.1
author=Katsushi Mitsutake (XENOCROSS AEROSPACE SYSTEM)
maintainer=Katsushi Mitsutake <mitutake@xenocross.com>
sentence=Teensy-based XENO controller library for HILS and fixed-wing control.
paragraph=TeensyXENO is a library for SBUS I/O, XenoController communication, PWM output, and HILS support on Teensy boards.
category=Communication
url=https://github.com/mitutake0422/TeensyXENO
architectures=teensy
